.Dd February 27, 2024
.Dt VP 1
.Os
.Sh NAME
.Nm vp
.Nd vowel plots
.Sh SYNOPSIS
.Nm
.Op Fl e
.Op Ar input Op Ar output
.Sh DESCRIPTION
.Nm
produces vowel plots.
It reads lines of text containing formant values and possibly labels,
and draws the corresponding dots in the vowel space.
An input line is expected to look like
.Bd -literal
too	315	1815
two	349	1517
do	347	1740
.Ed
.Pp
i.e. two numbers per line, meaning F1 and F2, possibly preceded by a label.
For every such line, a dot is drawn at those coordinates and labeled.
For diphthongs and glides, the line format is
.Bd -literal
goat	405	1249	360	1020
coat	451	1158	319	1077
soap	457	1253	365	 861
boat	475	 867	341	 838
.Ed
.Pp
i.e. four numbers per line,
meaning F1 and F2 of the first and second target,
possibly preceded by a label.
For every such line,
an arrow is drawn between the targets,
with the first one labeled.
.Pp
The input lines can be separated into groups by blank lines.
Typicaly, these are realizations of a single vowel.
Every such group can begin with a sequence of comments,
which are lines starting with
.Sq # .
If the group starts with comments, a nonempty comment on the
first comment line is used as a label for the whole group.
This can be used to label groups of vowels:
.Bd -literal
# ɪ
675 1850
564 2347
501 1786
522 1829
487 2080

# ə
472 1193
887 2656
432 1399
480 1753
548 1402
.Ed
.Pp
Groups are given different colors.
With the
.Fl e
option, an ellipse is drawn around a group.
.Pp
Without arguments,
.Nm
reads standard output and writes PostScript to standard output.
With a named
.Ar input
file,
.Nm
writes PostScript into an output file of the same basename.
With both
.Ar input
and
.Ar output
given,
.Nm
writes the output in a format determined by the output filename;
currently,
.Nm
produces PS and SVG files.
As a special case,
.Sq -
is considered the name of the standard input or output.
.Pp
The options are as follows:
.Pp
.Bl -tag -width xx -compact
.It Fl e
Draw an ellipse around every group of vowels.
.El
.Sh AUTHORS
.An Jan Starý Aq Mt hans@stare.cz
